#!/bin/bash

# @todo:
# - Swap cofig file reads into line-by-line; then IFS delim
# - ^^ Turn into util function

die() {
    echo "$1" >&2
    exit 1
}

check_file_exists() {
    local FILE=$1
    if [ -f "$FILE" ]; then
        echo "The file '$FILE' exists"
    else
        echo "The file '$FILE' does not exist"
    fi 
}