#!/bin/bash

# Stop script on: 
# - errors (-e), 
# - unset variables (-u)
# - pipe fails (-o pipefail)
set -euo pipefail

# ================
# Key task outline
# ================
# 1. Ask for sudo password
# 2. SSH key setup
# 3. Install dependencies: Xcode, Homebrew
# 4. Install Homebrew brews (also runs `brew update`) and casks
# 5. Install fonts (via Homebrew)
# 6. Run Homebrew clean-up tasks
# 7. Install/update Mac App Store applications
# 8. Install/update npm global packages
# 9. Set global .gitconfig details
# 10. Open sites for manual downloads


# =========
# CONSTANTS
# =========
APPS="$PWD/install/apps"
BREWS="$PWD/install/brews"
CASKS="$PWD/install/casks"
FONTS="$PWD/install/fonts"
MANUAL_INSTALLS="$PWD/install/manual"
NPM_PACKAGES="$PWD/install/npm"
UTILITIES="$PWD/utilities/utils"


# ============================================
# ERROR: Let the user know if the script fails
# ============================================
warn_script_failure() {
    FAILURE_CODE=$?
    test $FAILURE_CODE -ne 0 && message "[𝘅] macOS set-up script stopped." >&2
    exit $FAILURE_CODE
}


trap warn_script_failure EXIT


# ====================================
# DEBUGGING: Line-by-line step-through
# ====================================
# -- Uncomment trap line
# -- Run script with `bash -x ./start`
#    or add `-x` flag to `set` line, at top of this file
# trap '(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND")' DEBUG


# ===============
# SIGINT RESPONSE
# ===============
# -- Kill all background processes when CTRL+C pressed (OS sends SIGINT signal)
trap 'kill $(jobs -p)' INT


# ---

printf "
=================================================
****** Welcome to this macOS set-up script ******
=================================================
- Safe to run multiple times on the same machine
- It installs, upgrades, or skips packages based
  on what is already installed

WARNING: be sure to login to the Apple App Store,
if installing/updating App Store software.
-------------------------------------------------
\n"


# =================================
# LOAD UTILITIES: Warn if not found
# =================================
# shellcheck disable=SC1091
# shellcheck source=utilities/utils
if [ -f "$UTILITIES" ] && . "$UTILITIES"; then
    # Run system checks...
    check_bash_version
    check_internet_connection
else
    printf "\n ⚠️  %s file not found. Unable to continue set-up.\n" "$UTILITIES"
    exit 1
fi


# ================
# PROMPT: Password
# ================
message "Administrator password required"
ask_for_sudo


# ================
# CREATE: Profiles
# ================
create_zshrc


# ===============
# PROMPT: SSH key
# ===============
# chapter "Checking for SSH key..."
# @todo


# =====================
# INSTALL: Dependencies
# =====================
chapter "Installing dependencies"

# Xcode CLT
# =========
if type xcode-select &>/dev/null &&
    xpath=$( xcode-select --print-path ) &&
    test -d "${xpath}" && test -x "${xpath}"; then
    printf "\n"
    message_nochange "Xcode Command Line Tools already installed"
else
    printf "\n"
    message "Installing Xcode Command Line Tools..."
    xcode-select --install
    printf "
    =============================================================
    * Once completed, run script again to continue provisioning *
    =============================================================
    \n"
    # Ending script here allows Xcode CLT to fully install dependencies
    # before attempting NVM & Homebrew
    exit 0
fi


# ~/.bin directory
# ================
# if [ ! -d "$HOME/.bin/" ]; then
#     mkdir "$HOME/.bin"
# fi


# NVM/Node
# ========
# No harm in repeated runs of `nvm` installation; bonus checks for some updates
printf "\n"
message "Installing/updating NVM/Node..."
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash

# Ensure `nvm` command ready for immediate use
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Install/upgrade latest `node` & `npm`
printf "\n"
message "Installing/updating latest Node package..."
nvm install node
nvm use node &> /dev/null
nvm run node --version &> /dev/null


# Homebrew
# ========
if ! [ -x "$(command -v brew)" ]; then
    printf "\n"
    message "Installing Homebrew..."
    curl -fsSL 'https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh' | bash
    export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
    message_success "Homebrew package manager installed"
else
    printf "\n"
    message_nochange "Homebrew package manager already installed"
fi

if brew list --formula | grep -Fq brew-cask; then
    printf "\n"
    message "Uninstalling old Homebrew-Cask..."
    brew uninstall --force brew-cask
    message_success "Homebrew-Cask uninstalled"
fi


# =======================
# INSTALL: Homebrew Brews
# =======================
chapter "Installing Homebrew formulae"

if [ -e "$BREWS" ]; then
    for brew in $(<"$BREWS")
    do
        install_brews "$brew"
    done
else
    message "No additional command-line utilities requested."
fi


# ================
# UPDATE: Homebrew
# ================
chapter "Updating Homebrew formulae"
brew update


# =======================
# INSTALL: Homebrew Casks
# =======================
chapter "Installing applications via Homebrew"
if [ -e "$CASKS" ]; then
    for cask in $(<"$CASKS")
    do
        install_application_via_brew "$cask"
    done
else
    message "No additional applications requested."
fi


# =======================
# INSTALL: Homebrew Fonts
# =======================
chapter "Installing fonts via Homebrew"

if [ -e "$FONTS" ]; then
    message "Updating Homebrew fonts cask..."
    get_key_value_from_file "$FONTS" install_fonts
else
    message "No additional fonts requested."
fi


# =====================
# CLEAN: Homebrew files
# =====================
chapter "Clean-up Homebrew files"
brew cleanup 2> /dev/null


# ===================================
# INSTALL: Mac App Store applications
# ===================================
chapter "Installing Mac App Store applications"

if [ -x mas ]; then
    message_fail "Please install mas-cli first: brew mas ...skipping"
else
    if [ -e "$APPS" ]; then
      # Evaluation of store account/signin status was removed;
      # macOS (since version 12.x.x) no longer allows access via command-line
      get_key_value_from_file "$APPS" install_application_via_app_store
    else
        message "No Apple App Store applications requested."
    fi
fi


# ===========================
# Install NPM global packages
# ===========================
chapter "Installing global npm packages"

if [ -e "$NPM_PACKAGES" ]; then
    get_key_value_from_file "$NPM_PACKAGES" install_npm_packages
else
    message "No additional install/npm items requested."
fi


# =============================
# Set global .gitconfig details
# =============================
if type -P "git" &>/dev/null; then
    GIT_CONFIG="$HOME/.gitconfig"

    if [[ $(create_file "$GIT_CONFIG") ]]; then
        chapter "Set global .gitconfig details..."
        set_global_gitconfig_details
    fi
fi


# =======================
# Set global .m2 settings
# =======================
if type -P "mvn" &>/dev/null; then
    MVN_SETTINGS="$HOME/.m2/settings.xml"

    if [[ $(create_file "$MVN_SETTINGS") ]]; then
        chapter "Create Maven .m2/settings.xml file..."
        create_maven_settings_file
    fi
fi


# ===============================
# Open sites for manual downloads
# ===============================
chapter "Manual downloads"

if [ -e "$MANUAL_INSTALLS" ]; then
    if ask "Open manual downloads in browser?" N; then
        printf "\nOpening browser tabs:\n"
        get_key_value_from_file "$MANUAL_INSTALLS" open_manual_downloads
    else
        printf "\nYou have chosen not to open browser tabs at this time.\n"
    fi
fi


# ===========
# END MESSAGE
# ===========
printf "
===============================================
****** macOS set-up script run completed ******
===============================================
\n"

exit 0
